### ISSUE TITLE
pull wounds from the old flash soundboard

### ISSUE THREAD

**Issue by hayksaakian** [RustleOverwhelming/destiny_soundboard#2]
From here:

http://megaswf.com/serve/1001885/

**Comment by RustleOverwhelming** [comment]
It doesn't load for me unfortunately - that's partially why I made new one.

**Comment by hayksaakian** [comment]
I'll see if I can find an archive or something.

**Comment by hayksaakian** [comment]
Try this one someone backed up

https://dl.dropboxusercontent.com/u/22656330/1001885.swf

**Comment by hayksaakian** [comment]
Or

https://web.archive.org/web/20141116093852/http://megaswf.com/serve/1001885

**Comment by RustleOverwhelming** [comment]
I will add them soon AngelThump Thank you man.

**Comment by RustleOverwhelming** [comment]
Done and done. I'm closing this ticket.

**Comment by hayksaakian** [comment]
Klappa
